isotope support
eizemazal/butlerov pull request #6
Opened 2024-05-29 07:46 UTC by vetoshev

Added the ability to create isotopic atoms and get .mol ​​for them
The choice of isotope is made for atoms if they are present from stable ones. Fixed the function for converting text into a superscript because the current implementation did not work correctly for Arial

2024-05-29 13:39 UTC, BruceAndyLee commented
@vetoshev  don't forget to bump the version in package.json!

We\d like this change reflected on our landing :]

2024-05-30 07:03 UTC, eizemazal requested changes

2024-05-30 07:03 UTC, eizemazal commented on src/lib/elements.ts
> +    "F": new ChemicalElement("F", "Fluorine", 9, 18.9984032, [1], 1, []),
А вот моноизотопные элементы - у них пустой список. Вообще есть радиоактивные изотопы типа 18F, мы не будем их добавлять сюда? Если у тебя пока что  под рукой данные по элементам, может добавим их? Есть некоторые такие изотопы, которые имеют практическое значение (типа 32P, 18F)

2024-05-30 07:03 UTC, eizemazal commented on src/controller/MoleculeEditor.ts
> +                this.menu.add_button( new MenuButton(`${index + 1}`, `[${is}${vertex.element.symbol}]`, () => { this.commit_action(new ChangeVertexIsotopeAction(this.graph, vertex, is)); } ));
а может тут добавим `const iso_idx = int_to_superscript(is);` и будем показывать в меню верхним индексом изотоп?

2024-05-30 07:55 UTC, vetoshev commented on src/graph/Vertex.ts
> +        charge_text.setAttr("text", this.charge == -1 ? " - " : this.charge == 1 ? "+" : this.charge > 1 ? `${this._charge}+` : `${Math.abs(this._charge)}-`);
Там проблема с символом, который изначально читался - текущий шрифт его не поддерживает
поэтому использовать стал обычный минус
у него проблема что он "липнет" к левой части круга, поэтому обособил пробелами

2024-05-30 07:56 UTC, vetoshev commented on demo/test.html
> +                font-family: "Arial Unicode MS", Helvetica, sans-serif;
Возможно опять проблема с шрифтом - не понимаю
у меня выглядит так:
<img width="82" alt="Снимок экрана 2024-05-30 в 10 56 12" src="https://github.com/eizemazal/butlerov/assets/50217365/0e3b5bce-eeab-400f-90a2-a4884d797c78">

2024-05-30 08:10 UTC, vetoshev commented on src/lib/elements.ts
> +    "F": new ChemicalElement("F", "Fluorine", 9, 18.9984032, [1], 1, []),
Я сам поискал какие-то 
Давай добавим еще полезные действительно
Но кажется все мы добавить не сможем(да и не имеет смысла, наверное)

2024-05-31 15:55 UTC, vetoshev commented
Не совсем понимаю как писать лицензию 
Посмотрите - https://dejavu-fonts.github.io/

Butlerov Sans — License

The fonts are a modification of the DejaVu and Bitstream Vera fonts (see below). Changes to the DejaVu fonts are in the public domain. The explanation of copyright is provided on the Gnome page on Bitstream Vera fonts. Glyphs imported from the Arev fonts are the property of Tavmjung Bah (see below).

Bitstream Vera Fonts Copyright
Copyright (c) 2003 by Bitstream, Inc. All Rights Reserved. Bitstream Vera is a trademark of Bitstream, Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy of the fonts accompanying this license ("Fonts") and associated documentation files (the "Font Software"), to reproduce and distribute the Font Software, including without limitation the rights to use, copy, merge, publish, distribute, and/or sell copies of the Font Software, and to permit persons to whom the Font Software is furnished to do so, subject to the following conditions:

The above copyright and trademark notices and this permission notice shall be included in all copies of one or more of the Font Software typefaces.

The Font Software may be modified, altered, or added to, and in particular the designs of glyphs or characters in the Fonts may be modified and additional glyphs or characters may be added to the Fonts, only if the fonts are renamed to names not containing either the words "Bitstream" or the word "Vera".

This License becomes null and void to the extent applicable to Fonts or Font Software that has been modified and is distributed under the "Bitstream Vera" names.

The Font Software may be sold as part of a larger software package but no copy of one or more of the Font Software typefaces may be sold by itself.

THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL BITSTREAM OR THE GNOME FOUNDATION BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF THE USE OR INABILITY TO USE THE FONT SOFTWARE OR FROM OTHER DEALINGS IN THE FONT SOFTWARE.

Except as contained in this notice, the names of Gnome, the Gnome Foundation, and Bitstream Inc., shall not be used in advertising or otherwise to promote the sale, use or other dealings in this Font Software without prior written authorization from the Gnome Foundation or Bitstream Inc., respectively. For further information, contact: fonts at gnome dot org.

Arev Fonts Copyright
Original text

Copyright (c) 2006 by Tavmjong Bah. All Rights Reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy of the fonts accompanying this license ("Fonts") and associated documentation files (the "Font Software"), to reproduce and distribute the modifications to the Bitstream Vera Font Software, including without limitation the rights to use, copy, merge, publish, distribute, and/or sell copies of the Font Software, and to permit persons to whom the Font Software is furnished to do so, subject to the following conditions:

The above copyright and trademark notices and this permission notice shall be included in all copies of one or more of the Font Software typefaces.

The Font Software may be modified, altered, or added to, and in particular the designs of glyphs or characters in the Fonts may be modified and additional glyphs or characters may be added to the Fonts, only if the fonts are renamed to names not containing either the words "Tavmjong Bah" or the word "Arev".

This License becomes null and void to the extent applicable to Fonts or Font Software that has been modified and is distributed under the "Tavmjong Bah Arev" names.

The Font Software may be sold as part of a larger software package but no copy of one or more of the Font Software typefaces may be sold by itself.

THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL TAVMJONG BAH BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF THE USE OR INABILITY TO USE THE FONT SOFTWARE OR FROM OTHER DEALINGS IN THE FONT SOFTWARE.

Except as contained in this notice, the name of Tavmjong Bah shall not be used in advertising or otherwise to promote the sale, use or other dealings in this Font Software without prior written authorization from Tavmjong Bah. For further information, contact: tavmjong @ free . fr.

2024-09-08 09:13 UTC, eizemazal approved these changes

2024-09-08 09:13 UTC, merged